storage_profiles:
  default:
    name: Default Downloads
    paths:
    - ~/Downloads/HermesLink
    subfolders:
    - /home/prit/Downloads/HermesLink/testing
  movies:
    name: Movies
    paths:
    - ~/Videos/HermesLink_Movies
    subfolders:
    - /home/prit/Videos/HermesLink_Movies/new youtube
    - /home/prit/Videos/HermesLink_Movies/from youtube
