storage_profiles:
  default:
    name: Default Downloads
    paths:
    - ~/Downloads/HermesLink
    subfolders:
    - /home/prit/Downloads/HermesLink/testing
    - /home/prit/Downloads/HermesLink/watch
    - /home/prit/Downloads/HermesLink/Zip
    - /home/prit/Downloads/HermesLink/not_auto
    - /home/prit/Downloads/HermesLink/try1
    - /home/prit/Downloads/HermesLink/final
    - /home/prit/Downloads/HermesLink/final2
    - /home/prit/Downloads/HermesLink/Youtube
    - /home/prit/Downloads/HermesLink/from tab
    - /home/prit/Downloads/HermesLink/for tab
  movies:
    name: Movies
    paths:
    - /media/NewVolume/STUFF/Watch
    subfolders:
    - /media/NewVolume/STUFF/Watch/new youtube
    - /media/NewVolume/STUFF/Watch/from youtube
    - /media/NewVolume/STUFF/Watch/Series
    - /media/NewVolume/STUFF/Watch/Anime
